### PR TITLE
Fix #49 error of caused by Windows GCC compiler 

### LINKED ISSUE #49: error: linking with `x86_64-w64-mingw32.static.posix-gcc.exe` failed: exit code: 1
Hi, I am experiencing the following issue when trying to install the package from GitHub:

Compiling proc-macro2 v1.0.79
error: linking with `x86_64-w64-mingw32.static.posix-gcc.exe` failed: exit code: 1
  |

full output below:

── R CMD build ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\IAtanassov\AppData\Local\Temp\RtmpcTajag\remotes9603d321b60\bzhanglab-WebGestaltR-ad22bdb/DESCRIPTION'
─  preparing 'WebGestaltR':
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building 'WebGestaltR_1.0.0.tar.gz'
   Warnung: Datei 'WebGestaltR/configure' hatte keine Ausführungsrechte: korrigiert
   
* installing *source* package 'WebGestaltR' ...
** using staged installation
*** Checking if cargo is installed
*** Checking if cargo is newer than the required version
*** Checking if the required Rust target is installed
*** cargo is ok
** libs
using C compiler: 'gcc.exe (GCC) 13.2.0'
rm -Rf WebGestaltR.dll rust/target/x86_64-pc-windows-gnu/release/libWebGestaltR.a entrypoint.o
gcc  -I"C:/Users/IATANA~1/AppData/Local/Programs/R/R-44~1.0/include" -DNDEBUG  -I'C:/Users/IAtanassov/AppData/Local/Programs/R/R-4.4.0/library/Rcpp/include'   -I"C:/rtools44/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c entrypoint.c -o entrypoint.o
mkdir -p rust/target/libgcc_mock
# `rustc` adds `-lgcc_eh` flags to the compiler, but Rtools' GCC doesn't have
# `libgcc_eh` due to the compilation settings. So, in order to please the
# compiler, we need to add empty `libgcc_eh` to the library search paths.
#
# For more details, please refer to
# https://github.com/r-windows/rtools-packages/blob/2407b23f1e0925bbb20a4162c963600105236318/mingw-w64-gcc/PKGBUILD#L313-L316
touch rust/target/libgcc_mock/libgcc_eh.a
mkdir -p rust/target/x86_64-pc-windows-gnu/release/libgcc_mock && touch rust/target/x86_64-pc-windows-gnu/release/libgcc_mock/libgcc_eh.a
# CARGO_LINKER is provided in Makevars.ucrt for R >= 4.2
# vendoring (Note: to avoid NOTE of "Found the following hidden files and
# directories", .cargo needs to be created here)
if [ "yes" = "yes" ]; then \
  tar --extract --xz -f ./rust/vendor.tar.xz -C ./rust && \
    mkdir -p ./.cargo && \
    cp ./config.toml ./.cargo/config.toml; \
fi
if [ "" != "true" ]; then \
	export CARGO_HOME=/c/Users/IATANA~1/AppData/Local/Temp/RtmpWO9FXm/R.INSTALL1c6c4746565/WebGestaltR/src/.cargo; \
fi && \
	 export CARGO_TARGET_X86_64_PC_WINDOWS_GNU_LINKER="x86_64-w64-mingw32.static.posix-gcc.exe" && export LIBRARY_PATH="${LIBRARY_PATH};/c/Users/IATANA~1/AppData/Local/Temp/RtmpWO9FXm/R.INSTALL1c6c4746565/WebGestaltR/src/rust/target/x86_64-pc-windows-gnu/release/libgcc_mock" && export CARGO_HOME="/.cargo" &&  export CARGO_TARGET_X86_64_PC_WINDOWS_GNU_LINKER="x86_64-w64-mingw32.static.posix-gcc.exe" && \
	export LIBRARY_PATH="${LIBRARY_PATH};/c/Users/IATANA~1/AppData/Local/Temp/RtmpWO9FXm/R.INSTALL1c6c4746565/WebGestaltR/src/rust/target/libgcc_mock" && \
	cargo build --target=x86_64-pc-windows-gnu --jobs 2 --lib --release --manifest-path=./rust/Cargo.toml --target-dir rust/target --offline
   Compiling autocfg v1.1.0
   Compiling proc-macro2 v1.0.79
error: linking with `x86_64-w64-mingw32.static.posix-gcc.exe` failed: exit code: 1
  |
  = note: "x86_64-w64-mingw32.static.posix-gcc.exe" "-fno-use-linker-plugin" "-Wl,--dynamicbase" "-Wl,--disable-auto-image-base" "-m64" "-Wl,--high-entropy-va" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsbegin.o" "C:\\Users\\IATANA~1\\AppData\\Local\\Temp\\rustcnHkFcn\\symbols.o" "C:\\Users\\IATANA~1\\AppData\\Local\\Temp\\RtmpWO9FXm\\R.INSTALL1c6c4746565\\WebGestaltR\\src\\rust/target\\release\\build\\proc-macro2-5f0a4997c7c923dd\\build_script_build-5f0a4997c7c923dd.build_script_build.85eee1dd2bc8aeec-cgu.0.rcgu.o" "C:\\Users\\IATANA~1\\AppData\\Local\\Temp\\RtmpWO9FXm\\R.INSTALL1c6c4746565\\WebGestaltR\\src\\rust/target\\release\\build\\proc-macro2-5f0a4997c7c923dd\\build_script_build-5f0a4997c7c923dd.build_script_build.85eee1dd2bc8aeec-cgu.1.rcgu.o" "C:\\Users\\IATANA~1\\AppData\\Local\\Temp\\RtmpWO9FXm\\R.INSTALL1c6c4746565\\WebGestaltR\\src\\rust/target\\release\\build\\proc-macro2-5f0a4997c7c923dd\\build_script_build-5f0a4997c7c923dd.3pq5nudg1pkwx4dj.rcgu.o" "-L" "C:\\Users\\IATANA~1\\AppData\\Local\\Temp\\RtmpWO9FXm\\R.INSTALL1c6c4746565\\WebGestaltR\\src\\rust/target\\release\\deps" "-L" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "-Wl,-Bstatic" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libstd-1683fd82638343be.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libpanic_unwind-eb9f57b02a4c4ab2.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libobject-bc57e4cee7293166.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libmemchr-059e52a8c613d3af.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libaddr2line-efcbcb9a0789423d.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libgimli-80f85573e9bb766d.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_demangle-889f7a6efec9f4dc.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libstd_detect-09b18846a746f0af.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libhashbrown-31cd209190d703ef.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_std_workspace_alloc-e8404b0b8f6f4382.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libminiz_oxide-bc59235147d22ea0.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libadler-9cb2321a4772fcd2.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libunwind-2c6aa0136462e05b.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcfg_if-99fd3d0973d7ee73.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liblibc-9a98c6acdf8fd843.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liballoc-1515046c1e15d59c.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_std_workspace_core-bbd5c76512e13fe4.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcore-42718813a9191d38.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcompiler_builtins-e75b7451417035c0.rlib" "-Wl,-Bdynamic" "-lkernel32" "-ladvapi32" "-lkernel32" "-lntdll" "-luserenv" "-lws2_32" "-lkernel32" "-lws2_32" "-lkernel32" "-lgcc_eh" "-l:libpthread.a" "-lmsvcrt" "-lmingwex" "-lmingw32" "-lgcc" "-lmsvcrt" "-luser32" "-lkernel32" "-Wl,--nxcompat" "-L" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "-o" "C:\\Users\\IATANA~1\\AppData\\Local\\Temp\\RtmpWO9FXm\\R.INSTALL1c6c4746565\\WebGestaltR\\src\\rust/target\\release\\build\\proc-macro2-5f0a4997c7c923dd\\build_script_build-5f0a4997c7c923dd.exe" "-Wl,--gc-sections" "-no-pie" "-Wl,--strip-debug" "-nodefaultlibs" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsend.o"
  = note: C:\rtools44\x86_64-w64-mingw32.static.posix\bin/ld.exe: cannot find -lgcc_eh: No such file or directory
          collect2.exe: error: ld returned 1 exit status
          

error: could not compile `proc-macro2` (build script) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
make: *** [Makevars.win:38: rust/target/x86_64-pc-windows-gnu/release/libWebGestaltR.a] Error 101
ERROR: compilation failed for package 'WebGestaltR'
* removing 'C:/Users/IAtanassov/AppData/Local/Programs/R/R-4.4.0/library/WebGestaltR'
Warnmeldung:
In i.p(...) :
  Installation des Pakets ‘C:/Users/IATANA~1/AppData/Local/Temp/RtmpcTajag/file9606f9562ab/WebGestaltR_1.0.0.tar.gz’ hatte Exit-Status ungleich 0
> devtools::install_github("bzhanglab/WebGestaltR")
Downloading GitHub repo bzhanglab/WebGestaltR@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                             
2: CRAN packages only              
3: None                            
4: digest (0.6.35 -> 0.6.36) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 3
── R CMD build ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\IAtanassov\AppData\Local\Temp\RtmpcTajag\remotes9604b117926\bzhanglab-WebGestaltR-ad22bdb/DESCRIPTION'
─  preparing 'WebGestaltR':
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building 'WebGestaltR_1.0.0.tar.gz'
   Warnung: Datei 'WebGestaltR/configure' hatte keine Ausführungsrechte: korrigiert
   
* installing *source* package 'WebGestaltR' ...
** using staged installation
*** Checking if cargo is installed
*** Checking if cargo is newer than the required version
*** Checking if the required Rust target is installed
*** cargo is ok
** libs
using C compiler: 'gcc.exe (GCC) 13.2.0'
rm -Rf WebGestaltR.dll rust/target/x86_64-pc-windows-gnu/release/libWebGestaltR.a entrypoint.o
gcc  -I"C:/Users/IATANA~1/AppData/Local/Programs/R/R-44~1.0/include" -DNDEBUG  -I'C:/Users/IAtanassov/AppData/Local/Programs/R/R-4.4.0/library/Rcpp/include'   -I"C:/rtools44/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c entrypoint.c -o entrypoint.o
mkdir -p rust/target/libgcc_mock
# `rustc` adds `-lgcc_eh` flags to the compiler, but Rtools' GCC doesn't have
# `libgcc_eh` due to the compilation settings. So, in order to please the
# compiler, we need to add empty `libgcc_eh` to the library search paths.
#
# For more details, please refer to
# https://github.com/r-windows/rtools-packages/blob/2407b23f1e0925bbb20a4162c963600105236318/mingw-w64-gcc/PKGBUILD#L313-L316
touch rust/target/libgcc_mock/libgcc_eh.a
mkdir -p rust/target/x86_64-pc-windows-gnu/release/libgcc_mock && touch rust/target/x86_64-pc-windows-gnu/release/libgcc_mock/libgcc_eh.a
# CARGO_LINKER is provided in Makevars.ucrt for R >= 4.2
# vendoring (Note: to avoid NOTE of "Found the following hidden files and
# directories", .cargo needs to be created here)
if [ "yes" = "yes" ]; then \
  tar --extract --xz -f ./rust/vendor.tar.xz -C ./rust && \
    mkdir -p ./.cargo && \
    cp ./config.toml ./.cargo/config.toml; \
fi
if [ "" != "true" ]; then \
	export CARGO_HOME=/c/Users/IATANA~1/AppData/Local/Temp/RtmpYhfLhw/R.INSTALL30c060615f4d/WebGestaltR/src/.cargo; \
fi && \
	 export CARGO_TARGET_X86_64_PC_WINDOWS_GNU_LINKER="x86_64-w64-mingw32.static.posix-gcc.exe" && export LIBRARY_PATH="${LIBRARY_PATH};/c/Users/IATANA~1/AppData/Local/Temp/RtmpYhfLhw/R.INSTALL30c060615f4d/WebGestaltR/src/rust/target/x86_64-pc-windows-gnu/release/libgcc_mock" && export CARGO_HOME="/.cargo" &&  export CARGO_TARGET_X86_64_PC_WINDOWS_GNU_LINKER="x86_64-w64-mingw32.static.posix-gcc.exe" && \
	export LIBRARY_PATH="${LIBRARY_PATH};/c/Users/IATANA~1/AppData/Local/Temp/RtmpYhfLhw/R.INSTALL30c060615f4d/WebGestaltR/src/rust/target/libgcc_mock" && \
	cargo build --target=x86_64-pc-windows-gnu --jobs 2 --lib --release --manifest-path=./rust/Cargo.toml --target-dir rust/target --offline
   Compiling autocfg v1.1.0
   Compiling proc-macro2 v1.0.79
error: linking with `x86_64-w64-mingw32.static.posix-gcc.exe` failed: exit code: 1
  |
  = note: "x86_64-w64-mingw32.static.posix-gcc.exe" "-fno-use-linker-plugin" "-Wl,--dynamicbase" "-Wl,--disable-auto-image-base" "-m64" "-Wl,--high-entropy-va" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsbegin.o" "C:\\Users\\IATANA~1\\AppData\\Local\\Temp\\rustcpRvGVV\\symbols.o" "C:\\Users\\IATANA~1\\AppData\\Local\\Temp\\RtmpYhfLhw\\R.INSTALL30c060615f4d\\WebGestaltR\\src\\rust/target\\release\\build\\proc-macro2-5f0a4997c7c923dd\\build_script_build-5f0a4997c7c923dd.build_script_build.85eee1dd2bc8aeec-cgu.0.rcgu.o" "C:\\Users\\IATANA~1\\AppData\\Local\\Temp\\RtmpYhfLhw\\R.INSTALL30c060615f4d\\WebGestaltR\\src\\rust/target\\release\\build\\proc-macro2-5f0a4997c7c923dd\\build_script_build-5f0a4997c7c923dd.build_script_build.85eee1dd2bc8aeec-cgu.1.rcgu.o" "C:\\Users\\IATANA~1\\AppData\\Local\\Temp\\RtmpYhfLhw\\R.INSTALL30c060615f4d\\WebGestaltR\\src\\rust/target\\release\\build\\proc-macro2-5f0a4997c7c923dd\\build_script_build-5f0a4997c7c923dd.3pq5nudg1pkwx4dj.rcgu.o" "-L" "C:\\Users\\IATANA~1\\AppData\\Local\\Temp\\RtmpYhfLhw\\R.INSTALL30c060615f4d\\WebGestaltR\\src\\rust/target\\release\\deps" "-L" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "-Wl,-Bstatic" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libstd-1683fd82638343be.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libpanic_unwind-eb9f57b02a4c4ab2.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libobject-bc57e4cee7293166.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libmemchr-059e52a8c613d3af.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libaddr2line-efcbcb9a0789423d.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libgimli-80f85573e9bb766d.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_demangle-889f7a6efec9f4dc.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libstd_detect-09b18846a746f0af.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libhashbrown-31cd209190d703ef.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_std_workspace_alloc-e8404b0b8f6f4382.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libminiz_oxide-bc59235147d22ea0.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libadler-9cb2321a4772fcd2.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libunwind-2c6aa0136462e05b.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcfg_if-99fd3d0973d7ee73.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liblibc-9a98c6acdf8fd843.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liballoc-1515046c1e15d59c.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_std_workspace_core-bbd5c76512e13fe4.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcore-42718813a9191d38.rlib" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcompiler_builtins-e75b7451417035c0.rlib" "-Wl,-Bdynamic" "-lkernel32" "-ladvapi32" "-lkernel32" "-lntdll" "-luserenv" "-lws2_32" "-lkernel32" "-lws2_32" "-lkernel32" "-lgcc_eh" "-l:libpthread.a" "-lmsvcrt" "-lmingwex" "-lmingw32" "-lgcc" "-lmsvcrt" "-luser32" "-lkernel32" "-Wl,--nxcompat" "-L" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "-o" "C:\\Users\\IATANA~1\\AppData\\Local\\Temp\\RtmpYhfLhw\\R.INSTALL30c060615f4d\\WebGestaltR\\src\\rust/target\\release\\build\\proc-macro2-5f0a4997c7c923dd\\build_script_build-5f0a4997c7c923dd.exe" "-Wl,--gc-sections" "-no-pie" "-Wl,--strip-debug" "-nodefaultlibs" "C:\\Users\\IAtanassov\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsend.o"
  = note: C:\rtools44\x86_64-w64-mingw32.static.posix\bin/ld.exe: cannot find -lgcc_eh: No such file or directory
          collect2.exe: error: ld returned 1 exit status
          

error: could not compile `proc-macro2` (build script) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
make: *** [Makevars.win:38: rust/target/x86_64-pc-windows-gnu/release/libWebGestaltR.a] Error 101
ERROR: compilation failed for package 'WebGestaltR'
* removing 'C:/Users/IAtanassov/AppData/Local/Programs/R/R-4.4.0/library/WebGestaltR'
Warnmeldung:

-------------------------------------------------------------------------------------------------------------------------------------------------
> sessionInfo()
R version 4.4.0 (2024-04-24 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.utf8  LC_CTYPE=German_Germany.utf8    LC_MONETARY=German_Germany.utf8 LC_NUMERIC=C                    LC_TIME=German_Germany.utf8    

time zone: Europe/Berlin
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] tidyr_1.3.1        generics_0.1.3     utf8_1.2.4         stringi_1.8.4      digest_0.6.35      magrittr_2.0.3     evaluate_0.24.0    grid_4.4.0        
 [9] RColorBrewer_1.1-3 pkgload_1.3.4      fastmap_1.2.0      plyr_1.8.9         processx_3.8.4     pkgbuild_1.4.4     sessioninfo_1.2.2  limma_3.60.3      
[17] urlchecker_1.0.1   ps_1.7.6           promises_1.3.0     GGally_2.2.1       fansi_1.0.6        purrr_1.0.2        scales_1.3.0       cli_3.6.3         
[25] shiny_1.8.1.1      rlang_1.1.4        ellipsis_0.3.2     munsell_0.5.1      remotes_2.5.0      cachem_1.1.0       yaml_2.3.8         devtools_2.4.5    
[33] tools_4.4.0        memoise_2.0.1      dplyr_1.1.4        colorspace_2.1-0   ggplot2_3.5.1      httpuv_1.6.15      ggstats_0.6.0      curl_5.2.1        
[41] vctrs_0.6.5        R6_2.5.1           mime_0.12          lifecycle_1.0.4    stringr_1.5.1      fs_1.6.4           htmlwidgets_1.6.4  usethis_2.2.3     
[49] miniUI_0.1.1.1     pkgconfig_2.0.3    desc_1.4.3         callr_3.7.6        pillar_1.9.0       later_1.3.2        gtable_0.3.5       glue_1.7.0        
[57] profvis_0.3.8      Rcpp_1.0.12        statmod_1.5.0      tidyselect_1.2.1   tibble_3.2.1       xfun_0.45          rstudioapi_0.16.0  knitr_1.47        
[65] xtable_1.8-4       htmltools_0.5.8.1  rmarkdown_2.27     compiler_4.4.0    

Best wishes,
Ilian

### PR DESCRIPTION
**Pull request by iblacksand**
Fixes error caused by gcc compiler provided by Rtools. Tested on R's provided windows check service.

### CODE REVIEW

**Comment by iblacksand** [comment]
Errors with CRAN checks caused by depreciated R APIs. Being tracked in https://github.com/extendr/extendr/issues/806.

**Comment by iblacksand** [comment]
Build errors due to non-api calls. Fixed in the master branch of [extendr/rextendr](https://github.com/extendr/rextendr). Will update this PR with the latest version of rextendr when it is released.

**Comment by iblacksand** [comment]
This PR aims to address the linker issue in #49. The exact issue is hard to replicate, as it passes checks in my GitHub action, and passes both R-release and R-devel on the win-builder service (https://win-builder.r-project.org/).

There has been progress in this PR, as the current master branch will fail to build on win-builder. After I updated `src/Makevars.win.in` to follow the https://github.com/r-rust/hellorust structure, it builds without any errors. However, it still doesn't fix the linker issue the user faces. 

I think the last piece of the puzzle is `lgcc_eh`, which from my understanding is not provided by Rtools. From my previous `Makevars.win.in`, the fix was to create an empty `lgcc_eh.a` file that is in the `LIBRARY_PATH` variable. This is going to be my next attempt to fix.

If you have any suggestions for how to fix this error, I would welcome any comments.

**Comment by CGMossa** [comment]
Yes! We routinely update the package configuration in `rextendr` (the R-package for using Rust in R with extendr). I'd really just recommend..

```r
remotes::install_github("extendr/rextendr")
usethis::create_package("exampleRustRpkg")
rextendr::use_extendr()
```
And have a look at those files, copy them over, and adjust them to meet your package's needs.

Sorry, but these things are constantly changing, and we couldn't get it right the first time.

**Comment by CGMossa** [comment]
The reason I'm also here, is because I think you'd have some issues here with extracting info from the shell in Makevars. Something about using backticks for this for compatibility.. I don't recall the details of this, unfortunately. 

PS: found it 
image

See https://cran.r-project.org/doc/manuals/R-exts.html#Writing-portable-packages-1

**Comment by iblacksand** [comment]
This branch has solved some other peoples issues with windows, so I will merge this PR. I will work on a fix in a separate branch.

**Pull request merged**
